from .dashboard_tab   import DashboardTab
from .statistics_tab  import StatisticsTab
from .processes_tab   import ProcessesTab
from .connections_tab import ConnectionsTab
from .diagnostics_tab import DiagnosticsTab
from .devices_tab     import DevicesTab
from .alerts_tab      import AlertsTab
from .settings_tab    import SettingsTab
from .tray_icon       import TrayIcon
